# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  forest_env_secret: 8f602192ee4bf6f95b32340b35b4b012eaf9c7d854bc66594ddfba1c78ff1ef6
  forest_auth_secret: h3UkYOA-vlDHhjeJZY51vg
  secret_key_base: 9e264f5ed02acf79fe1b8a1417c554c52a8c02fe86539ce50df3aaeb6d56036c9b149d58e0b100209be3c9b90cedfffb3770be03fe5e3a7558a7e0ee5c745f39

test:
  secret_key_base: ea262d3d6883e7ec7b59fd0893ba9a9bd1d51d1d873dec41f95737621e1ba546364d811e4eafe238cf5261c18e63bd213f51e2dd7f57d03f6cbed460295ade13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
